name: Build/Test

on:
  pull_request:
    branches: [ master, release ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-preview.2.21155.3
      - name: Install dependencies
        run: dotnet restore -v m
      - name: Build
        run: dotnet build --configuration Release --no-restore -v m

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-preview.2.21155.3
      - name: Test
        run: dotnet test --no-restore -v m     
