name: MVC Image

on:
  pull_request:
    branches: [ master, relase ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file ./src/Dotnet6.GraphQL4.Store.WebMVC/Dockerfile --tag my-image-name:$(date +%s)
